services:
  - type: web
    name: student-performance-ml
    env: python
    buildCommand: pip install -r requirements.txt && pip install -e .
    startCommand: gunicorn application:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0